on:
    push:
        tags:
            - "*"
    workflow_dispatch:

name: Publish to VS Marketplace
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
            - run: npm install
            - name: Publish to Visual Studio Marketplace
              uses: HaaLeo/publish-vscode-extension@v2
              id: publish
              with:
                  pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
                  registryUrl: https://marketplace.visualstudio.com
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: |
                      ${{ steps.publish.outputs.vsixPath }}
